### ISSUE TITLE
Your demo website has been flagged as deceptive.

### ISSUE THREAD

**Issue by zephiowl** [AAAAAXfda-zz/discord-ui#1]
Hello as you can see in the attached screenshot your demo website (found on your readme) links to a site that has been reported as deceptive. You may take a look at the details regarding this report [here](https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fdiscord-ui-herbemalveillante.vercel.app%2F)
 
![image](https://user-images.githubusercontent.com/66909997/186326126-e4d4e711-c8cf-48c9-91a1-4488cc373943.png)

**Comment by AAAAAXfda-zz** [comment]
@Xanthus58 Please ignore the warning. It's 100% safe, it's a simple discord UI replica.

**Comment by zephiowl** [comment]
My browser quite literally wont let me go to sites that have been flagged. You may want to get the flag resolved by contacting google. Granted thats a plugin i installed myself to stay more secure but its still an issue that should probably be dealt with.

You could even move it to something like git-hub pages where it wont get flagged. Has free hosting; people can view the code that makes up the website and even has ssl certification. But that's entirely up to you.

**Comment by AAAAAXfda-zz** [comment]
> My browser quite literally wont let me go to sites that have been flagged. You may want to get the flag resolved by contacting google. Granted thats a plugin i installed myself to stay more secure but its still an issue that should probably be dealt with.
> 
> You could even move it to something like git-hub pages where it wont get flagged. Has free hosting; people can view the code that makes up the website and even has ssl certification. But that's entirely up to you.

Will do. Thanks for reporting this.
